# Generated by Django 4.2.6 on 2023-10-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critiques', '0003_rename_time_created_review_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='image',
            new_name='images',
        ),
    ]
